version: "3.0"

services:
  api:
    container_name: "game-ai-agent"
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - ollama
    deploy:
      resources:
        limits:
          memory: 4g
  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 8g